#*************************************************
#****************datasets args********************
#*************************************************
filepaths:
  model_path:
    base: workspace/models
    model: omr
  feature_path:
    base: ../data/processed-feature
    seq: ../data/processed-feature/sequence-annotation
  raw_path:
    osmd: ../data/raw/osmd-dataset-v1.0.0
  test_path: ../data/test/test_omr

jsonkeys:
  measure_list: measureList

measure: measure
measure_height: 120

channels: 1
max_height: 128
max_width: 256
max_seq_len: 24

batch_size: 16
epoch: 200

# augmentation args
augment:
  awgn_sigma: 0.04
  et_small_alpha_training: 16
  et_small_sigma_evaluation: 10
  et_large_alpha_training: 1000
  et_large_sigma_evaluation: 80